Repository mujik-tigers/course-registration-system, pull requests merged in 2023-12, with the labels that each got.

#5 Feature: 로그인 기능 구현 완료
  .github/workflows/test-report.yml
  build.gradle
  src/docs/asciidoc/auth.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/site/courseregistrationsystem/auth/StudentSession.java
  src/main/java/site/courseregistrationsystem/auth/application/AuthService.java
  src/main/java/site/courseregistrationsystem/auth/application/SessionManager.java
  src/main/java/site/courseregistrationsystem/auth/dto/LoginForm.java
  src/main/java/site/courseregistrationsystem/auth/infrastructure/SessionStorage.java
  src/main/java/site/courseregistrationsystem/auth/presentation/AuthController.java
  src/main/java/site/courseregistrationsystem/auth/presentation/CookieProperties.java
  src/main/java/site/courseregistrationsystem/config/PropertiesConfig.java
  src/main/java/site/courseregistrationsystem/config/RedisConfig.java
  src/main/java/site/courseregistrationsystem/exception/CustomException.java
  src/main/java/site/courseregistrationsystem/exception/ErrorType.java
  src/main/java/site/courseregistrationsystem/exception/GlobalExceptionHandler.java
  src/main/java/site/courseregistrationsystem/exception/auth/InvalidPasswordException.java
  src/main/java/site/courseregistrationsystem/exception/auth/NonexistenceSessionException.java
  src/main/java/site/courseregistrationsystem/exception/auth/NonexistenceStudentIdException.java
  src/main/java/site/courseregistrationsystem/student/Student.java
  src/main/java/site/courseregistrationsystem/student/infrastructure/StudentRepository.java
  src/main/java/site/courseregistrationsystem/util/api/ApiResponse.java
  src/main/java/site/courseregistrationsystem/util/api/ResponseMessage.java
  src/main/java/site/courseregistrationsystem/util/encryption/Aes256Manager.java
  src/main/java/site/courseregistrationsystem/util/encryption/Aes256Properties.java
  src/main/java/site/courseregistrationsystem/util/encryption/BCryptManager.java
  src/main/java/site/courseregistrationsystem/validator/PasswordFormatCheck.java
  src/main/java/site/courseregistrationsystem/validator/StudentIdFormatCheck.java
  src/test/java/site/courseregistrationsystem/CourseRegistrationSystemApplicationTests.java
  src/test/java/site/courseregistrationsystem/RestDocsSupport.java
  src/test/java/site/courseregistrationsystem/auth/application/AuthServiceTest.java
  src/test/java/site/courseregistrationsystem/auth/application/SessionManagerTest.java
  src/test/java/site/courseregistrationsystem/auth/presentation/AuthControllerTest.java
  src/test/java/site/courseregistrationsystem/util/encryption/Aes256ManagerTest.java
  src/test/java/site/courseregistrationsystem/util/encryption/BCryptManagerTest.java
Labels: week1

#13 Feature: 공지사항 페이지에 필요한 기능들 구현
  src/docs/asciidoc/api/auth.adoc
  src/docs/asciidoc/api/clock.adoc
  src/docs/asciidoc/api/session.adoc
  src/docs/asciidoc/api/student.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/site/courseregistrationsystem/auth/presentation/AuthController.java
  src/main/java/site/courseregistrationsystem/clock/dto/CurrentServerTime.java
  src/main/java/site/courseregistrationsystem/clock/presentation/ClockController.java
  src/main/java/site/courseregistrationsystem/config/WebConfig.java
  src/main/java/site/courseregistrationsystem/department/Department.java
  src/main/java/site/courseregistrationsystem/department/infrastructure/DepartmentRepository.java
  src/main/java/site/courseregistrationsystem/exception/ErrorType.java
  src/main/java/site/courseregistrationsystem/exception/auth/NonexistenceSessionCookieException.java
  src/main/java/site/courseregistrationsystem/exception/student/NonexistenceStudentException.java
  src/main/java/site/courseregistrationsystem/interceptor/LoginCheckInterceptor.java
  src/main/java/site/courseregistrationsystem/student/Grade.java
  src/main/java/site/courseregistrationsystem/student/Student.java
  src/main/java/site/courseregistrationsystem/student/application/StudentService.java
  src/main/java/site/courseregistrationsystem/student/dto/StudentInformation.java
  src/main/java/site/courseregistrationsystem/student/presentation/StudentController.java
  src/main/java/site/courseregistrationsystem/util/ProjectConstant.java
  src/main/java/site/courseregistrationsystem/util/api/ResponseMessage.java
  src/main/java/site/courseregistrationsystem/util/resolver/Login.java
  src/main/java/site/courseregistrationsystem/util/resolver/LoginArgumentResolver.java
  src/test/java/site/courseregistrationsystem/RestDocsSupport.java
  src/test/java/site/courseregistrationsystem/auth/presentation/AuthControllerTest.java
  src/test/java/site/courseregistrationsystem/clock/presentation/ClockControllerTest.java
  src/test/java/site/courseregistrationsystem/student/application/StudentServiceTest.java
  src/test/java/site/courseregistrationsystem/student/presentation/StudentControllerTest.java
Labels: week2

#15 Feature: 종합 강의 시간표 조회 기능 구현 완료
  .gitignore
  src/docs/asciidoc/api/lecture.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/site/courseregistrationsystem/lecture/Lecture.java
  src/main/java/site/courseregistrationsystem/lecture/application/LectureService.java
  src/main/java/site/courseregistrationsystem/lecture/dto/LectureDetail.java
  src/main/java/site/courseregistrationsystem/lecture/dto/LectureFilterOptions.java
  src/main/java/site/courseregistrationsystem/lecture/dto/LectureSchedulePage.java
  src/main/java/site/courseregistrationsystem/lecture/infrastructure/LectureRepository.java
  src/main/java/site/courseregistrationsystem/lecture/presentation/LectureController.java
  src/main/java/site/courseregistrationsystem/professor/Professor.java
  src/main/java/site/courseregistrationsystem/professor/infrastructure/ProfessorRepository.java
  src/main/java/site/courseregistrationsystem/schedule/DayOfWeek.java
  src/main/java/site/courseregistrationsystem/schedule/Period.java
  src/main/java/site/courseregistrationsystem/schedule/Schedule.java
  src/main/java/site/courseregistrationsystem/schedule/infrastructure/ScheduleRepository.java
  src/main/java/site/courseregistrationsystem/student/Grade.java
  src/main/java/site/courseregistrationsystem/subject/Subject.java
  src/main/java/site/courseregistrationsystem/subject/SubjectDivision.java
  src/main/java/site/courseregistrationsystem/subject/infrastructure/SubjectRepository.java
  src/main/java/site/courseregistrationsystem/util/api/ResponseMessage.java
  src/test/java/site/courseregistrationsystem/RestDocsSupport.java
  src/test/java/site/courseregistrationsystem/auth/application/AuthServiceTest.java
  src/test/java/site/courseregistrationsystem/auth/application/SessionManagerTest.java
  src/test/java/site/courseregistrationsystem/lecture/application/LectureServiceTest.java
  src/test/java/site/courseregistrationsystem/lecture/presentation/LectureControllerTest.java
Labels: feat, docs, test, week2
